AWSTemplateFormatVersion: "2010-09-09"
Description: "世界一丁寧なAWS解説をCloudformationでコード化" #講師作成サンプルテンプレート

# AWSの各リソースの定義
Resources:
  # VPCの定義
  RaiseTechLive10VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: raisetech-live10-vpc

  # サブネットの定義
  RaiseTechLive10PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      VpcId: !Ref RaiseTechLive10VPC
      # サブネット単位でiPv4パブリックアドレスの割り当てを有効化
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: raisetech-live10-public-subnet-1a
    Metadata:
      AWS::CloudFormation::Designer:
        id: d7aa5763-884d-474d-a58e-e89846f7075a

  RaiseTechLive10PublicSubnet1d:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ap-northeast-1d
      VpcId: !Ref RaiseTechLive10VPC
      # サブネット単位でiPv4パブリックアドレスの割り当てを有効化
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: raisetech-live10-public-subnet-1d
    Metadata:
      AWS::CloudFormation::Designer:
        id: 53a3c8ff-60b2-4ebd-ac3f-af8f5d477e33

  # RDS用プライベートサブネット1dの定義
  RaiseTechLive10RdsSubnet1d:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1d
      VpcId: !Ref RaiseTechLive10VPC
      Tags:
        - Key: Name
          Value: raisetech-live10-rds-private-subnet-1d
    Metadata:
      AWS::CloudFormation::Designer:
        id: 431e856f-cdba-4222-b438-

