# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.0.0 

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  executeCloudFormation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_DEFAULT_REGION
      # - run:
      #     name: "Check Stack Existence"
      #     command: |
      #       STACK_NAME="SampleStack"
      #       REGION="ap-northeast-1"
            
      #       # Check if the stack exists
      #       if aws cloudformation describe-stacks --stack-name $STACK_NAME --region $REGION >/dev/null 2>&1; then
      #         echo "Stack $STACK_NAME already exists. Skipping stack creation."
      #         exit 0
      #       else
      #         echo "Stack $STACK_NAME does not exist. Proceeding with stack creation."
      #         # Execute the stack creation command here
      #         aws cloudformation create-stack --stack-name $STACK_NAME --region $REGION --template-body file://sample_stack.yml
      #       fi
      - run:
          name: deploy Cloudformation
          command: |
            set -x
            aws cloudformation deploy --stack-name SampleStack --template sample_stack.yml
     
     
  ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ac:66:0a:e2:ce:28:9e:b7:21:18:ea:a2:36:a4:4e:66"
      - ansible-playbook/install:
          version: "2.9.23"
      - ansible-playbook/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: playbook.yml
          playbook-options: "-u ec2-user --private-key ~/.ssh/id_rsa"
      
  install-ruby:  
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install:
          version: '2.7'

  install-Serverspec:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: "Install Serverspec"
          command: gem install serverspec
      - run:
          name: "Run Serverspec"
          command: rake spec

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  raisetech-circleci:
    jobs:
      - executeCloudFormation
      - ansible:
          requires:
            - executeCloudFormation
      - install-ruby:
          requires:
            - ansible
      - install-Serverspec:
          requires:
            - install-ruby